### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by elazzour** [Legimet/nPDF#15]
Hello dear friend. First of all, I would like to congratulate you on the work you have done on the subject of npdf, however, I would like to know whether you think that there will be a search option in the future, as it is the only thing missing. Either way, thank you and great job.

**Comment by Legimet** [comment]
This is a duplicate of #13.
And yes, I plan to make searching available in the next version.

**Comment by elazzour** [comment]
oh i'm very sorry for the duplicate :( and thank you for the answer
