### ISSUE TITLE
Font compatibility

### ISSUE THREAD

**Issue by AlexandreFrance** [Legimet/nPDF#7]
nPDF can't read text in my PDF.
How can i add new font ? 
or can you add a default one ?

**Comment by Legimet** [comment]
Could you post a link to your PDF? I will take a look at it.

Can On Wednesday, February 25, 2015 10:50:36 AM AlexandreFrance wrote:

**Comment by AlexandreFrance** [comment]
http://gofile.me/2Mepj/RuQK29cP

**Comment by Legimet** [comment]
This looks like an upstream bug (in MuPDF) and seems to have been fixed in 
MuPDF's git repository. I will try to cherry-pick the fix.

**Comment by Legimet** [comment]
Sorry for forgetting about this, but MuPDF 1.7 was released 2 days ago, so it will be fixed soon.

**Comment by Legimet** [comment]
I updated to MuPDF 1.7, so this *should* be fixed. Unfortunately, I didn't save your PDF and can't test it. Please comment on whether it works now.

**Comment by AlexandreFrance** [comment]
Thank you for your update but I have no time to compile and test it. Can you try with my PDF ? http://gofile.me/2Mepj/mTvY3TDZ




MORITZ Alexandre





De : Legimet
Envoyé : ‎dimanche‎ ‎21‎ ‎juin‎ ‎2015 ‎00‎:‎44
À : Legimet/nPDF
Cc : Alexandre MORITZ





I updated to MuPDF 1.7, so this should be fixed. Unfortunately, I didn't save your PDF and can't test it. Please comment on whether it works now.

**Comment by adriweb** [comment]
That still made it crashed under Firebird, with the very latest nPDF, under OS 3.9 :(
I'll let Legimet try to debug it further.

**Comment by Legimet** [comment]
I just opened it in nPDF, and It works for me. Closing this issue.
